const HOST = "http://137.184.128.54/api";
//const HOST = "http://localhost:3000/api";

export default {
  "day_trip": {
    "sign_up": `${HOST}/sign_up`,
    "sign_in": `${HOST}/sign_in`,
    "delete_user": `${HOST}/logins/{0}`,
    "getProfileInfo": `${HOST}/profile_info/{0}?profile={1}`,
    "updateProfileInfo": `${HOST}/profile_info/{0}`,
    "getCarMarks": `${HOST}/car_brands`,
    "getCarModels": `${HOST}/car_brands/{0}/models`,
    "getTips": `${HOST}/tips?type={0}&lang={1}`,
    "getDestinations": `${HOST}/destinations?lang={0}`,
    "saveDriverPreregData": `${HOST}/driver_infos`,
    "getHeroes": `${HOST}/heroes?lang={0}`,
    "getTrips": `${HOST}/trips?login_id={0}&is_top_choice={1}&offset={2}&limit={3}&lang={4}`,
    "searchTrips": `${HOST}/trips?query={0}&lang={1}`,
    "getTripDetail": `${HOST}/trips/{0}?login_id={1}&lang={2}`,
    "getHitTheRoad": `${HOST}/hit_the_road?lang={0}`,
    "saveTrip": `${HOST}/save_trip`,
    "driverInfos": `${HOST}/driver_infos/{0}`,
    "driverProgress": `${HOST}/driver_progress?id={0}`,
    "driverProgressDetails": `${HOST}/view_driver_progress?id={0}&section_type={1}`,
    "getSavedTrips": `${HOST}/saved_trips?login_id={0}`,
    "getCountryCities": `${HOST}/country_cities?city={0}`,
    "getIndividualUser": `${HOST}/profile_info/{0}?profile=user_profile&user_type={1}`,
    "getCalendarSettings": `${HOST}/calendar_settings/{0}`,
    "updateCalendarSettings": `${HOST}/calendar_settings/{0}`,
    "searchForDriver": `${HOST}/search_drivers?date={0}&travelers={1}&price_range={2}&trip_id={3}&offset={4}&limit={5}&lang={6}&currency={7}`,
    "loadPricesList": `${HOST}/price_list?is_trip={0}`,
    "addTripReview": `${HOST}/trip_review`,
    "addDriverReview": `${HOST}/driver_review`,
    "confirmTripBookingCheckout": `${HOST}/booked_trips`,
    "getBookedTrips": `${HOST}/booked_trips?user_id={0}&utype={1}`,
    "getBookedTripsCount": `${HOST}/booked_trips_count?user_id={0}&utype={1}`,
    "getBookedTrip": `${HOST}/booked_trips/{0}?utype={1}`,
    "resendConfirmation": `${HOST}/resend_confirmation?email={0}`,
    "getConversation": `${HOST}/conversations`,
    // "loadConversations": `${HOST}/conversations?user_id={0}&lang={1}`,
    "loadConversationsByName": `${HOST}/conversations?user_id={0}&contact_name={1}&lang={2}`,
    "viewConversation":  `${HOST}/conversations/{0}`,
    "createMessage": `${HOST}/messages/{0}`,
    "getConversationMessages":  `${HOST}/messages/{0}?user_id={1}`,
    "getHelpContentList": `${HOST}/contents?type={0}&lang={1}`,
    "getHelpContentById": `${HOST}/contents/{0}?type={1}&lang={2}`,
    "convertTripPrice": `${HOST}/convert_price?trip_price={0}&currency={1}`,
  }
}
